### ISSUE TITLE
Are Patreon Exclusive Pages Possible?

### ISSUE THREAD

**Issue by WeirdFoodStudio** [hkeward/weirdfoodstudio#12]
# Less of an issue and more of me asking "Is this a thing?"

I'm thinking of making the comic page and the (eventual, if possible) blog page exclusive to Patreon subscribers (when I get them hahaha) and I want to converse with you about whether that's possible and what it might look like.

**Comment by hkeward** [comment]
It's possible, but would require a good deal of work. I think this is something we could discuss further once your Patreon is set up/once you have supporters; in the short-term, I would recommend making use of Patreon's own internal mechanisms for showing content at different tier levels (i.e. make blog posts within Patreon, where you can set the tiers that are able to see each type of post).

Closing for now.
