### ISSUE TITLE
Adjust Boarder Sizes on Homepage

### ISSUE THREAD

**Issue by WeirdFoodStudio** [hkeward/weirdfoodstudio#8]
# Goal is Consistency

Attached is an image of the front page that I've notated detailing what I'd like done, if possible. 
Basically, I'd like a wider boarder around the items in the homepage, more in line with the space existing on the left side.
We had discussed this issue briefly, and I'm willing to go for a larger boarder if you suggest. Most of what I want is an equal amount of space on each side.

![github_issueimage_boarders](https://user-images.githubusercontent.com/119975636/206265882-2c231a5d-6c32-452a-a663-3fb6e5b49a68.jpg)

**Comment by hkeward** [comment]
Before:
![title_before](https://user-images.githubusercontent.com/13265645/210197963-b1925614-0bd8-4fdc-a073-56f5b03e7b2a.png)

After (constant 28 px surrounding the full page, including above the navbar):
![title_after](https://user-images.githubusercontent.com/13265645/210197966-03666c15-5cb4-47aa-bed0-46ca6145eabf.png)

@WeirdFoodStudio if you think the navbar should not be included in the constant border (i.e. only move the title down to the consistent border height, leave the navbar the smaller distance from the edge of the screen as previously) let me know here and I'll revert.
